import Navbar from "./components/Navbar";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Banner from "./components/Banner";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-lightBlue min-h-screen flex flex-col">
        <Navbar />
        <div className="flex flex-1 justify-center">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
